-- MySQL Script generated by MySQL Workbench
-- Fri Dec  7 17:43:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clubesocial
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clubesocial` ;

-- -----------------------------------------------------
-- Schema clubesocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clubesocial` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `clubesocial` ;

-- -----------------------------------------------------
-- Table `clubesocial`.`plano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubesocial`.`plano` ;

CREATE TABLE IF NOT EXISTS `clubesocial`.`plano` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `votoAssembleia` TINYINT(1) NOT NULL,
  `votoEleicao` TINYINT(1) NOT NULL,
  `permiteDependente` TINYINT(1) NOT NULL,
  `nome` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `clubesocial`.`associado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubesocial`.`associado` ;

CREATE TABLE IF NOT EXISTS `clubesocial`.`associado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_plano` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `endereco` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `telefone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_242824C9CFE385AE` (`id_plano` ASC) VISIBLE,
  CONSTRAINT `FK_242824C9CFE385AE`
    FOREIGN KEY (`id_plano`)
    REFERENCES `clubesocial`.`plano` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `clubesocial`.`parentesco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubesocial`.`parentesco` ;

CREATE TABLE IF NOT EXISTS `clubesocial`.`parentesco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeParentesco` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `clubesocial`.`dependente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubesocial`.`dependente` ;

CREATE TABLE IF NOT EXISTS `clubesocial`.`dependente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `associado_id` INT(11) NOT NULL,
  `parentesco_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `associado_id`),
  INDEX `fk_dependente_associado1_idx` (`associado_id` ASC) VISIBLE,
  INDEX `fk_dependente_parentesco1_idx` (`parentesco_id` ASC) VISIBLE,
  CONSTRAINT `fk_dependente_associado1`
    FOREIGN KEY (`associado_id`)
    REFERENCES `clubesocial`.`associado` (`id`),
  CONSTRAINT `fk_dependente_parentesco1`
    FOREIGN KEY (`parentesco_id`)
    REFERENCES `clubesocial`.`parentesco` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `clubesocial`.`mensalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubesocial`.`mensalidade` ;

CREATE TABLE IF NOT EXISTS `clubesocial`.`mensalidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_associado` INT(11) NULL DEFAULT NULL,
  `data` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `mes` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `ano` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_F026810E26EC1A4D` (`id_associado` ASC) VISIBLE,
  CONSTRAINT `FK_F026810E26EC1A4D`
    FOREIGN KEY (`id_associado`)
    REFERENCES `clubesocial`.`associado` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `clubesocial`.`ocorrencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubesocial`.`ocorrencia` ;

CREATE TABLE IF NOT EXISTS `clubesocial`.`ocorrencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_associado` INT(11) NULL DEFAULT NULL,
  `id_dependente` INT(11) NULL DEFAULT NULL,
  `motivo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dias` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_9333DAB126EC1A4D` (`id_associado` ASC) VISIBLE,
  INDEX `IDX_9333DAB19B500D0B` (`id_dependente` ASC) VISIBLE,
  CONSTRAINT `FK_9333DAB126EC1A4D`
    FOREIGN KEY (`id_associado`)
    REFERENCES `clubesocial`.`associado` (`id`),
  CONSTRAINT `FK_9333DAB19B500D0B`
    FOREIGN KEY (`id_dependente`)
    REFERENCES `clubesocial`.`dependente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
